### ISSUE TITLE
Ban console.* methods

### ISSUE THREAD

**Issue by KevinGrandon** [pinterest-web/eslint-config-pinterest#12]
Right now they're just a warning, let's make them an error?

**Comment by chrislloyd** [comment]
I think the reason why they were warnings was because we legitimately use them in some places (mainly node code). Maybe a better approach is to set them as errors, then individually whitelist legitimate cases?

**Comment by arthuralee** [comment]
yeah, I think we already whitelist the rule in the most obvious cases (the logger module). We can do a sweep some time and kick the rule up to the error level

**Comment by KevinGrandon** [comment]
This was resolved in: https://github.com/pinterest-web/eslint-config-pinterest/commit/794b63fe9ced16841166771ddb8a1bc66032f953
