### ISSUE TITLE
Consider doing pure alpha sorting on sort-prop-types

### ISSUE THREAD

**Issue by KevinGrandon** [pinterest-web/eslint-config-pinterest#8]
Currently our sort-prop-types definition looks like: 
```
        'react/sort-prop-types': [2, {
            'callbacksLast': true,
            'ignoreCase': true,
            'requiredFirst': true,
        }],
```

This means that in some cases, we might have some component that looks like:
```js
MyComponent.propTypes = {
  selected: PropTypes.bool.isRequired,
  onChange: PropTypes.func.isRequired,
  anotherProp: PropTypes.string,
  zebraProp: PropTypes.string,
  onOptionalEvent: PropTypes.func
};
```

I feel that `callbacksLast` and `requiredFirst` being true cause this list to be not as readable when they are false. The same list when both are false:

```js
MyComponent.propTypes = {
  anotherProp: PropTypes.string,
  onChange: PropTypes.func.isRequired,
  onOptionalEvent: PropTypes.func
  selected: PropTypes.bool.isRequired,
  zebraProp: PropTypes.string,
};
```

**Comment by azulus** [comment]
I agree

**Comment by zackargyle** [comment]
I agree with yanking out `requiredFirst`, but I do like `callbacksLast`.

```
MyComponent.propTypes = {
  anotherProp: PropTypes.string,
  selected: PropTypes.bool.isRequired,
  zebraProp: PropTypes.string,
  onChange: PropTypes.func.isRequired,
  onOptionalEvent: PropTypes.func
};
```

**Comment by azulus** [comment]
if we add a visual space above callbacks and always prefix them with on, I'm fine with that.

**Comment by azulus** [comment]
```
MyComponent.propTypes = {
  anotherProp: PropTypes.string,
  selected: PropTypes.bool.isRequired,
  zebraProp: PropTypes.string,

  onChange: PropTypes.func.isRequired,
  onOptionalEvent: PropTypes.func
};
```

**Comment by KevinGrandon** [comment]
I don't think it's as nice as pure alpha, but I'm ok with leaving callbacks on the end as well. Some spacing or delimiter makes it nicer, and it should be easy enough to add an option to the linter to support requiring it.

**Comment by zackargyle** [comment]
Let's just go pure alpha. Easier for developers since they are familiar with it from scss attributes already.

**Comment by adamburmister** [comment]
:+1: on last proposal, with or without \n

**Comment by chrislloyd** [comment]
:+1: on alpha list from me too, will help with diffs
